BookShop/Models/AuthorisationErrorViewModel.cs
namespace BookShop.Models
{
    public class AuthorisationErrorViewModel
    {
        public string ErrorMessage { get; set; }

        public string RedirectUrl { get; set; }
    }
}

BookShop/Models/BookViewModel.cs
using System.ComponentModel.DataAnnotations;
using BookShop.Domain.Entities;

namespace BookShop.Models
{
    public class BookViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Название")]
        public string Name { get; set; }

        [Display(Name = "Автор")]
        public string AuthorName { get; set; }

        [Display(Name = "Стоимость")]
        public int Price { get; set; }

        public byte[]? Image { get; set; }


    }
}

BookShop/Models/BuyBookViewModel.cs
namespace BookShop.Models
{
    public class BuyBookViewModel
    {
        public List<BookViewModel> Books { get; set; }
     

        public BuyBookViewModel()
        {
            Books = new List<BookViewModel>();
        }
    }
}

BookShop/Models/ErrorViewModel.cs
namespace BookShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookShop/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookShop.Models
{
    public class LogInViewModel
    {
        [Required(ErrorMessage = "Введите имя пользователя")]
        [Display(Name = "Имя пользователя")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Введите пароль")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }
    }
}

BookShop/Models/MainPageViewModel.cs
namespace BookShop.Models
{
    public class MainPageViewModel
    {

    }
}

BookShop/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookShop.Models
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage ="Введите имя пользователя")]
        [MaxLength(20, ErrorMessage ="Имя пользователя должно иметь длину менее 20 символов")]
        [MinLength(3, ErrorMessage = "Имя пользователя должно иметь длину более 3 символов")]
        [Display(Name = "Имя пользователя")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage ="Введите пароль")]
        [MaxLength(10, ErrorMessage ="Пароль должен иметь длинну менее 10 символов")]
        [MinLength(4, ErrorMessage = "Пароль должен иметь длинну более 4 символов.")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage ="Подтвердите пароль")]
        [Compare("Password" ,ErrorMessage ="Пароли не совпадают") ]
        [Display(Name = "Подтвердите пароль")]
        public string ConfirmPassword { get; set; }


    }
}

BookShop/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Security.Claims;
using BookShop.DataBaseLogic;
using BookShop.Domain.Entities;
using BookShop.Models;
using BookShop.Services;
using BookShop.Services.Interfaces;

namespace BookShop.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _accountService.Register(model);

                if (response.StatusCode == Domain.Enum.StatusCode.OK)                     
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                       new ClaimsPrincipal(response.Data));

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", response.Description);
            }

            return View(model);

        }

        [HttpGet]
        public ActionResult Authorisation() => View();

        [HttpPost]
        public async Task<IActionResult> Authorisation(LogInViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _accountService.Login(model);

                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                       new ClaimsPrincipal(response.Data));

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", response.Description);
            }

            return View(model);
        }

        public ActionResult AuthorisationError(AuthorisationErrorViewModel model)
        {
            return View(model);
        }
    }
}

BookShop/Controllers/BookListController.cs
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BookShop.Domain.Entities;
using BookShop.Models;
using BookShop.Services.Interfaces;

namespace BookShop.Controllers
{
    public class BookListController : Controller
    {
        private readonly ILogger<BookListController> _logger;

        private readonly IBookService _bookService;

        public BookListController(ILogger<BookListController> logger, IBookService bookService)
        {
            _logger = logger;

            _bookService = bookService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult BuyBook()
        {
            BuyBookViewModel model = new BuyBookViewModel();

            _bookService.SetBookInfo(model);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> BuyBook(int id)
        {

            await _bookService.BuyBookbyId(id);

            return RedirectToAction("Index", "Home");
        }
    }
}

BookShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using BookShop.Domain.Entities;
using BookShop.Models;

namespace BookShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookShop/Views/BookList/BuyBook.cshtml
@model BuyBookViewModel
@{
    ViewData["Title"] = "Каталог";
}
<body div class="back-image">

<div class="navbar">
<ul>
   
    @foreach (var book in Model.Books)
    {
        var path = $"/images/{book.Id}.png";
        <li>
            <img src = @path height="250" width="150"><br>
            <strong>@book.Name</strong> <br> <i> Автор: @book.AuthorName <br> Цена: @book.Price</i> RUB
            <form asp-controller="BookList" asp-action="BuyBook" method="post">
                <input type="hidden" name="id" value="@book.Id" />
                <button type="submit" class="btn btn-primary">Купить</button>
            </form>
        </li>
    }
</ul>
</div>
</body>

BookShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<body div class="back-image">
<div class="text-center">
    <h2>Привет!</h2>
    </div>
    <p>
        Добро пожаловать в "Книжную гавань" - вашу книжную лавку в 2023 году! Мы предлагаем широкий ассортимент книг на любой вкус и возраст, а также приятные цены и высокое качество обслуживания. Несмотря на то, что мы открылись недавно, мы совершенно не уступаем нашим более опытным конкурентам. Приходите к нам и убедитесь в этом сами! Мы гарантируем, что вы найдете здесь все, что нужно для вашей любимой занятия - чтения. В "Книжной гавани" мы заботимся о каждом клиенте и всегда рады помочь вам с выбором книги или ответить на любые вопросы. Посетите наш магазин и окунитесь в мир увлекательных историй и захватывающих приключений!
    </p>
    <p>
        Наши контакты:
        <br>
        <a href="mailto: bookharbor@yandex.ru">Наша почта</a>
        <br>
        <a href="mailto: bookharbor@gmail.com">Наша почта</a>
        <br>
        8 (999) 444-22-33 — круглосуточно
    </p>
   
    </body>

BookShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href ="~/css/style.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css"/>

</head>
<body>
    <header>
        <ul class="nav">
            <li class="nav-image">
                <img src="/images/logo1.png" width="50" height="50"/>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Мой аккаунт</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="BookList" asp-action="BuyBook">Каталог</a>
            </li>

        </ul>             
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>